language: Swift
osx_image: xcode12.1
xcode_project: Utils/Utils.xcworkspace
xcode_scheme: Utils

jobs:
  include:
    - stage: Build
      name: Build
      script:
        - set -o pipefail
        - cd Utils
        - make init
        - xcodebuild test -scheme Utils -workspace Utils.xcworkspace/ -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' | xcpretty -c
        - swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios12.1-simulator" -Xswiftc "-lswiftUIKit"
    - stage: Pod Lib Lint
      name: Pod Lib Lint
      script:
        - travis_wait 20 pod lib lint
  
